<?php

declare (strict_types=1);
namespace common\classes\Billing;

interface Billing_Point_Interface
{
    /**
     * @return array
     */
    public static function get_supported_operations();
    /**
     * @param string $operation 'generate-product-info' / 'translate-product-info'
     * @param string $domainKey domain key generated by installation
     * @param string $appKey AppShop key generated in oscommerce.com
     * @param $extraParams
     * @return void
     */
    public static function check_operation_available(string $operation, string $domain_key, string $app_key, $extra_params = null);
    public static function do_operation_finished(string $operation, string $domain_key, string $app_key, $extra_params = null);
}