<?php

declare (strict_types=1);
/**
 * This file is part of osCommerce ecommerce platform.
 * osCommerce the ecommerce
 *
 * @link https://www.oscommerce.com
 * @copyright Copyright (c) 2000-2022 osCommerce LTD
 *
 * Released under the GNU General Public License
 * For the full copyright and license information, please view the LICENSE.TXT file that was distributed with this source code.
 */
namespace common\classes\Billing;

use common\helpers\Assert;
class Billing_Manager
{
    private static $billing_points = null;
    private static function get_billing_points()
    {
        if (is_null(self::$billing_points)) {
            self::$billing_points = [];
            foreach (\common\helpers\Hooks::get_list('billing/billing-points') as $filename) {
                include $filename;
                // use self::addBillingPoint()
            }
        }
        return self::$billing_points;
    }
    private static function get_billing_point_check(string $operation)
    {
        $points = self::get_billing_points();
        Assert::key_exists($points, $operation, "Billing point not found for {$operation}");
        return $points[$operation];
    }
    private static function add_billing_point($billing_point_class)
    {
        Assert::class_implements($billing_point_class, \common\classes\Billing\Billing_Point_Interface::class);
        foreach ($billing_point_class::get_supported_operations() as $operation) {
            Assert::assert(!array_key_exists($operation, self::get_billing_points()), "Billing point already exist for {$operation}");
            self::$billing_points[$operation] = $billing_point_class;
        }
    }
    /**
     * @param string $operation 'generate-product-info' / 'translate-product-info'
     * @param string $domainKey domain key generated by installation
     * @param string $appKey AppShop key generated in oscommerce.com
     * @param $extraParams
     * @return void
     */
    public static function check_operation_available(string $operation, string $domain_key, string $app_key, $extra_params = null)
    {
        $res = self::check_operation_available_safe($operation, $domain_key, $app_key, $extra_params);
        if ((isset($res['result']) && $res['result'] === false || isset($res['success']) && $res['success'] === false) && (isset($res['message']) || isset($res['error']))) {
            throw new \yii\base\User_Exception($res['message'] ?? $res['error'] ?? 'Unknown error');
        }
    }
    public static function check_operation_available_safe(string $operation, string $domain_key, string $app_key, $extra_params = null)
    {
        try {
            $billing_point = self::get_billing_point_check($operation);
            return $billing_point::check_operation_available($operation, $domain_key, $app_key, $extra_params);
        } catch (\Throwable $e) {
            \common\helpers\Php::log_error($e, __CLASS__ . '::' . __FUNCTION__);
            return self::get_internal_error_result();
        }
    }
    public static function do_operation_finished(string $operation, string $domain_key, string $app_key, $extra_params = null)
    {
        try {
            $billing_point = self::get_billing_point_check($operation);
            $billing_point::do_operation_finished($operation, $domain_key, $app_key, $extra_params);
        } catch (\Throwable $e) {
            \common\helpers\Php::log_error($e, __CLASS__ . '::' . __FUNCTION__);
        }
    }
    public static function get_internal_error_result($message = 'Internal error')
    {
        return ['result' => false, 'message' => $message];
    }
}